### ISSUE TITLE
Unhandled exception number 128 occurred in onPacketSending

### ISSUE THREAD

**Issue by Overwrite987** [TestSender/HunterAntiCheat#3]
[22:32:49 ERROR]: [HunterAntiCheat-RU] Unhandled exception number 128 occurred in onPacketSending(PacketEvent) for HunterAntiCheat-RU
java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/server/TemporaryPlayer
        at com.hunter.hunteranticheat.event.PacketListener.onPacketSending(PacketListener.java:65) ~[HunterAntiCheat-RU.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2271) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2247) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.internalTeleport(ServerGamePacketListenerImpl.java:1869) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1364) ~[fusion-1.19.3.jar:git-Fusion-"68c42d1"]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1228) ~[fusion-1.19.3.jar:git-Fusion-"68c42d1"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1673) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[fusion-1.19.3.jar:git-Fusion-"68c42d1"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[fusion-1.19.3.jar:git-Fusion-"68c42d1"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[fusion-1.19.3.jar:git-Fusion-"68c42d1"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[fusion-1.19.3.jar:git-Fusion-"68c42d1"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[fusion-1.19.3.jar:git-Fusion-"68c42d1"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[fusion-1.19.3.jar:git-Fusion-"68c42d1"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[fusion-1.19.3.jar:git-Fusion-"68c42d1"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[fusion-1.19.3.jar:git-Fusion-"68c42d1"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.injector.server.TemporaryPlayer
        ... 34 more

**Comment by TestSender** [comment]
Плагин давно обновлён, дело в устаревшей зависимости ProtocolLib, прощу прощения за долгий ответ, не успеваю
